# Generated by Django 4.0 on 2021-12-10 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_req_docu', models.CharField(max_length=150, verbose_name='student_req_docu')),
                ('req_date', models.CharField(max_length=200, verbose_name='req_date')),
                ('req_time_choices', models.CharField(blank=True, choices=[('8:00 - 9:00 AM', '8:00 - 9:00 AM'), ('9:00 - 10:00 AM', '9:00 - 10:00 AM'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM'), ('2:00 - 3:00 PM', '2:00 - 3:00 PM'), ('3:00 - 4:00 PM', '3:00 - 4:00 PM')], max_length=200, null=True)),
                ('status_field', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], max_length=200, null=True, verbose_name='status_field')),
                ('user_field', models.CharField(default='TUPC180127', max_length=30, verbose_name='user_field')),
                ('date_posted', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'student_appointment',
            },
        ),
        migrations.CreateModel(
            name='User_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='student_id')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('student_email', models.EmailField(blank=True, max_length=200, verbose_name='student_email')),
                ('student_pass', models.CharField(max_length=200, verbose_name='student_pass')),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
    ]
